automation:
    alias: Emulate LongPress on FoH Switches
    description: ''
    trigger:
      - platform: event
        event_type: hue_event
        event_data:
          type: initial_press
      - platform: event
        event_type: hue_event
        event_data:
          type: long_press
    condition: []
    action:
      - wait_for_trigger:
          - platform: event
            event_type: hue_event
            event_data:
              id: |
                {% set long_release=false %}{{trigger.event.data.id}}
              device_id: |
                {{trigger.event.data.device_id}}
              unique_id: |
                {{trigger.event.data.unique_id}}
              type: short_release
              subtype: |
                {{trigger.event.data.subtype}}
        timeout:
          milliseconds: 1000
      - choose:
          - conditions:
              - condition: template
                value_template: '{{wait.trigger.event.data.type == "short_release"}}'
            sequence:
              - event: hue_event
                event_data:
                  id: |
                    {{trigger.event.data.id}}
                  device_id: |
                    {{trigger.event.data.device_id}}
                  unique_id: |
                    {{trigger.event.data.unique_id}}
                  type: |
                    {% if trigger.event.data.type == "initial_press" %}
                      short_press
                    {% else %}
                      long_press_release
                    {% endif %}
                  subtype: |
                    {{trigger.event.data.subtype}}
        default:
          - event: hue_event
            event_data:
              id: |
                {{trigger.event.data.id}}
              device_id: |
                {{trigger.event.data.device_id}}
              unique_id: |
                {{trigger.event.data.unique_id}}
              type: long_press
              subtype: |
                {{trigger.event.data.subtype}}
    mode: restart
